#!/usr/bin/env bash
# ============================================
# Home Vault — Rocky Linux Setup Script
# ============================================
# Run as root or with sudo:
#   sudo bash setup.sh
# ============================================

set -euo pipefail

APP_NAME="home-vault"
APP_DIR="/opt/${APP_NAME}"
APP_USER="homevault"
DATA_DIR="/var/lib/${APP_NAME}"
LOG_DIR="/var/log/${APP_NAME}"
SERVICE_FILE="/etc/systemd/system/${APP_NAME}.service"
ENV_FILE="${APP_DIR}/.env"
NODE_MAJOR=20

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $1"; exit 1; }

# ─── Preflight ─────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then fail "This script must be run as root (sudo bash setup.sh)"; fi

echo ""
echo "  ╔══════════════════════════════════════════╗"
echo "  ║      🏠 Home Vault — Rocky Linux Setup   ║"
echo "  ╚══════════════════════════════════════════╝"
echo ""

# ─── Step 1: Install Node.js 20 ───────────────────────────────
info "Checking Node.js..."
if command -v node &>/dev/null; then
  CURRENT_NODE=$(node -v | cut -d. -f1 | tr -d 'v')
  if [[ "$CURRENT_NODE" -ge 18 ]]; then
    ok "Node.js $(node -v) already installed"
  else
    warn "Node.js $(node -v) is too old, installing v${NODE_MAJOR}..."
    INSTALL_NODE=true
  fi
else
  INSTALL_NODE=true
fi

if [[ "${INSTALL_NODE:-false}" == "true" ]]; then
  info "Installing Node.js ${NODE_MAJOR} from NodeSource..."
  dnf install -y curl
  curl -fsSL https://rpm.nodesource.com/setup_${NODE_MAJOR}.x | bash -
  dnf install -y nodejs
  ok "Node.js $(node -v) installed"
fi

# ─── Step 2: Install build tools for better-sqlite3 ───────────
info "Installing build tools for native modules..."
dnf groupinstall -y "Development Tools" 2>/dev/null || dnf install -y gcc gcc-c++ make python3
ok "Build tools ready"

# ─── Step 3: Create service user ──────────────────────────────
info "Creating service user '${APP_USER}'..."
if id "${APP_USER}" &>/dev/null; then
  ok "User '${APP_USER}' already exists"
else
  useradd --system --shell /usr/sbin/nologin --home-dir "${APP_DIR}" --create-home "${APP_USER}"
  ok "User '${APP_USER}' created"
fi

# ─── Step 4: Create directories ──────────────────────────────
info "Creating directories..."
mkdir -p "${APP_DIR}" "${DATA_DIR}" "${LOG_DIR}"
ok "Directories created: ${APP_DIR}, ${DATA_DIR}, ${LOG_DIR}"

# ─── Step 5: Copy application files ──────────────────────────
info "Copying application files to ${APP_DIR}..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Copy everything except setup files and data
rsync -a --exclude='setup.sh' \
         --exclude='home-vault.service' \
         --exclude='.env' \
         --exclude='node_modules' \
         --exclude='dist' \
         --exclude='data' \
         "${SCRIPT_DIR}/" "${APP_DIR}/"

ok "Files copied"

# ─── Step 6: Configure environment ───────────────────────────
if [[ -f "${ENV_FILE}" ]]; then
  warn ".env already exists — keeping existing config"
else
  info "Generating .env with secure JWT secret..."
  JWT_SECRET=$(openssl rand -hex 64)
  cat > "${ENV_FILE}" <<EOF
# Home Vault — Production Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

NODE_ENV=production
PORT=3000

# JWT Secret (auto-generated — keep this safe!)
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=8h

# Session cookie
COOKIE_NAME=hv_session

# Database (persistent storage in /var/lib)
DB_PATH=${DATA_DIR}/home-vault.db

# Password hashing (12 rounds is a good balance of speed/security)
BCRYPT_ROUNDS=12

# Rate limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100
AUTH_RATE_LIMIT_MAX=10
EOF
  ok ".env created with secure JWT secret"
fi

# ─── Step 7: Install dependencies ────────────────────────────
info "Installing npm dependencies (this may take a minute)..."
cd "${APP_DIR}"
npm ci --omit=dev 2>&1 | tail -1
# Also install dev deps temporarily for the build step
npm install --save-dev @vitejs/plugin-react vite 2>&1 | tail -1
ok "Dependencies installed"

# ─── Step 8: Build frontend ─────────────────────────────────
info "Building frontend..."
npx vite build 2>&1 | tail -3
ok "Frontend built to ${APP_DIR}/dist"

# Remove dev dependencies after build
info "Pruning dev dependencies..."
npm prune --omit=dev 2>&1 | tail -1
ok "Dev dependencies removed"

# ─── Step 9: Initialize database ─────────────────────────────
info "Initializing database..."
cd "${APP_DIR}"
node server/db-init.js
ok "Database initialized at ${DATA_DIR}/home-vault.db"

# ─── Step 10: Set permissions ─────────────────────────────────
info "Setting file permissions..."
chown -R "${APP_USER}:${APP_USER}" "${APP_DIR}" "${DATA_DIR}" "${LOG_DIR}"
chmod 600 "${ENV_FILE}"
chmod 700 "${DATA_DIR}"
ok "Permissions set (${APP_USER} owns everything, .env is 600)"

# ─── Step 11: Install systemd service ────────────────────────
info "Installing systemd service..."
cp "${SCRIPT_DIR}/home-vault.service" "${SERVICE_FILE}" 2>/dev/null || \
cat > "${SERVICE_FILE}" <<EOF
[Unit]
Description=Home Vault — Secure Inventory & Document Tracker
Documentation=https://github.com/your-repo/home-vault
After=network.target

[Service]
Type=simple
User=${APP_USER}
Group=${APP_USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=/usr/bin/node server/index.js
Restart=always
RestartSec=5

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=${DATA_DIR} ${LOG_DIR}

# Resource limits
LimitNOFILE=65535
TimeoutStartSec=30
TimeoutStopSec=30

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${APP_NAME}

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
ok "Systemd service installed"

# ─── Step 12: SELinux context (if enforcing) ──────────────────
if command -v getenforce &>/dev/null && [[ "$(getenforce)" != "Disabled" ]]; then
  info "Setting SELinux contexts..."
  semanage fcontext -a -t httpd_sys_content_t "${APP_DIR}(/.*)?" 2>/dev/null || true
  semanage fcontext -a -t httpd_sys_rw_content_t "${DATA_DIR}(/.*)?" 2>/dev/null || true
  restorecon -Rv "${APP_DIR}" "${DATA_DIR}" 2>/dev/null || true

  # Allow Node.js to bind to port 3000
  semanage port -a -t http_port_t -p tcp 3000 2>/dev/null || \
  semanage port -m -t http_port_t -p tcp 3000 2>/dev/null || true
  ok "SELinux contexts applied"
else
  info "SELinux not enforcing — skipping"
fi

# ─── Step 13: Firewall ───────────────────────────────────────
if command -v firewall-cmd &>/dev/null; then
  info "Opening port 3000 in firewalld..."
  firewall-cmd --permanent --add-port=3000/tcp 2>/dev/null || true
  firewall-cmd --reload 2>/dev/null || true
  ok "Firewall port 3000 opened"
else
  warn "firewalld not found — manually open port 3000 if needed"
fi

# ─── Step 14: Start service ──────────────────────────────────
info "Starting Home Vault..."
systemctl enable "${APP_NAME}"
systemctl start "${APP_NAME}"

sleep 2

if systemctl is-active --quiet "${APP_NAME}"; then
  ok "Home Vault is running!"
else
  warn "Service may not have started. Check: journalctl -u ${APP_NAME} -f"
fi

# ─── Done ─────────────────────────────────────────────────────
echo ""
echo "  ╔══════════════════════════════════════════════════╗"
echo "  ║            🏠 Home Vault — Setup Complete!       ║"
echo "  ╠══════════════════════════════════════════════════╣"
echo "  ║                                                  ║"
echo "  ║  URL:      http://$(hostname -I | awk '{print $1}'):3000           "
echo "  ║  Config:   ${ENV_FILE}"
echo "  ║  Database: ${DATA_DIR}/home-vault.db"
echo "  ║  Logs:     journalctl -u ${APP_NAME} -f"
echo "  ║                                                  ║"
echo "  ║  Commands:                                       ║"
echo "  ║    systemctl status  ${APP_NAME}                 ║"
echo "  ║    systemctl restart ${APP_NAME}                 ║"
echo "  ║    systemctl stop    ${APP_NAME}                 ║"
echo "  ║                                                  ║"
echo "  ╚══════════════════════════════════════════════════╝"
echo ""
